 <?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @title      Cielo pagamento com cartão de crédito (Brazil)
 * @category   payment
 * @package    Nitroecom_Cielo
 * @copyright  Copyright (c) 2017 Nitroecom (https://www.nitroecom.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Lucas Oliveira - Nitro e-com <www.nitroecom.com.br>
 */
?>

<ul id="payment_form_nitrocielo" class="nitroecom_cielo form-list" style="display: none;">
    <li><?php echo $this->getMensagem(); ?></li>

    <?php if(Mage::getStoreConfig('payment/nitrocielo/display_card')): ?>
        <input name="payment[bandeira_cielo]" type="hidden" id="" value="" class="radio_cielo">
    <?php else: ?>
        <li class="card-logo">
        <?php if(in_array('Visa',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_visa">
                <input name="payment[bandeira_cielo]" type="radio" value="Visa" id="nitrocielo_cartao_visa" class="validate-one-required-by-name cartao16digitos">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Visa.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Master',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_mastercard">
                <input name="payment[bandeira_cielo]" type="radio" value="Master" id="nitrocielo_cartao_mastercard" class="validate-one-required-by-name cartao16digitos">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Master.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Diners',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_diners">
                <input name="payment[bandeira_cielo]" type="radio" value="Diners" id="nitrocielo_cartao_diners" class="validate-one-required-by-name">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Diners.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Discover',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_discover">
                <input name="payment[bandeira_cielo]" type="radio" value="Discover" id="nitrocielo_cartao_discover" class="validate-one-required-by-name cartao16digitos">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Discover.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Elo',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_elo">
                <input name="payment[bandeira_cielo]" type="radio" value="Elo" id="nitrocielo_cartao_elo" class="validate-one-required-by-name cartao16digitos">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Elo.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Amex',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_amex">
                <input name="payment[bandeira_cielo]" type="radio" value="Amex" id="nitrocielo_cartao_amex" class="validate-one-required-by-name">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Amex.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('JCB',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_jcb">
                <input name="payment[bandeira_cielo]" type="radio" value="JCB" id="nitrocielo_cartao_jcb" class="validate-one-required-by-name cartao16digitos">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/JCB.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Aura',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_aura">
                <input name="payment[bandeira_cielo]" type="radio" value="Aura" id="nitrocielo_cartao_aura" class="validate-one-required-by-name">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Aura.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Hipercard',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_hipercard">
                <input name="payment[bandeira_cielo]" type="radio" value="Hipercard" id="nitrocielo_cartao_hipercard" class="validate-one-required-by-name">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Hipercard.svg'); ?>">
            </label>
        <?php endif; ?>
        <?php if(in_array('Hiper',$this->getBandeiras())): ?>
            <label for="nitrocielo_cartao_hiper">
                <input name="payment[bandeira_cielo]" type="radio" value="Hiper" id="nitrocielo_cartao_hiper" class="validate-one-required-by-name">
                <img src="<?php echo $this->getSkinUrl('images/nitrocielo/Hiper.svg'); ?>">
            </label>
        <?php endif; ?>
    </li>
    <?php endif; ?>
    
    <li>
        <label for="nitrocielo_numero_cartao_cielo" class="required">
            <em>*</em><?php echo $this->__('Número do Cartão de Crédito') ?>
        </label>
        <div class="input-box">
            <input type="text" pattern="\d*" id="nitrocielo_numero_cartao_cielo" name="payment[numero_cartao_cielo]" title="<?php echo $this->__('Número do Cartão de Crédito') ?>" class="input-text required-entry validate-cc-number" value="" autocomplete="off">
        </div>
    </li>
    
    <li>
        <label for="nitrocielo_portador_cielo" class="required">
            <em>*</em><?php echo $this->__('Titular Cartão') ?>
        </label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Titular Cartão') ?>" class="input-text name-card required-entry" id="nitrocielo_portador_cielo" name="payment[portador_cielo]" value="" autocomplete="off">
        </div>
    </li>

    <li>
        <label for="nitrocielo_expiracao_mes_cielo" class="required">
            <em>*</em><?php echo $this->__('Data de Validade') ?>
        </label>
        <div class="input-box">
            <div class="v-fix">
                <select id="nitrocielo_expiracao_mes_cielo" name="payment[expiracao_mes_cielo]" class="required-entry">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>

            <div class="v-fix">
                <select id="nitrocielo_expiracao_ano_cielo" name="payment[expiracao_ano_cielo]" class="required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>

    <li>
        <label for="nitrocielo_codigo_seguranca_cielo" class="required">
            <em>*</em><?php echo $this->__('Código de Segurança') ?>
        </label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" pattern="\d*" title="<?php echo $this->__('Código de Segurança') ?>" class="input-text required-entry" id="nitrocielo_codigo_seguranca_cielo" name="payment[codigo_seguranca_cielo]" value="" autocomplete="off">
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('O que é isso?') ?></a>
        </div>
    </li>

    <li>
        <label for="nitrocielo_parcelas_cielo" class="required">
            <em>*</em><?php echo $this->__('Parcelas') ?>
        </label>
        <div class="input-box">
            <span class="mes-cartao n-parcelas">
                <select id="nitrocielo_parcelas_cielo" name="payment[parcelas_cielo]"></select>
            </span>
        </div>
    </li>
</ul>


<script type="text/javascript">

    jQuery('.cvv-what-is-this').click(function( event ) {
        jQuery('#payment-tool-tip').show();
    });
    
    jQuery('#payment-tool-tip-close').click(function( event ) {
        jQuery('#payment-tool-tip').hide();
    });

    // Aviso - Valores estão sendo atualizados
    $('nitrocielo_parcelas_cielo').update('Calculando valores... Aguarde!');

    $('nitrocielo_parcelas_cielo').on('change',function(){if(typeof payment == "object"){payment.update()}});
    
    // Cria uma insância do objeto js do módulo
    var valor            = '<?php echo $this->getValorTotal(); ?>';
    var parcelas         = '<?php echo $this->getMaximoParcelas(); ?>';
    var juros            = '<?php echo $this->getJurosParcela(); ?>';
    var parcelassemjuros = '<?php echo $this->getParcelassemJuros(); ?>';
    var valorminimo      = '<?php echo $this->getValorMinimoParcela(); ?>';
    var descontoavista   = '<?php echo $this->getDescontoaVista(); ?>';

    $('nitrocielo_parcelas_cielo').update(
        NitroecomCielo.getParcelasHtml(valor, parcelas, juros, parcelassemjuros,valorminimo,descontoavista)
    );

    <?php if(!Mage::getStoreConfig('payment/nitrocielo/display_card')): ?>
        mascaraCartao = new MaskedInput('#nitrocielo_numero_cartao_cielo', '9999 9999 9999 9999');
        mascaraCod    = new MaskedInput('#nitrocielo_codigo_seguranca_cielo', '999');

        jQuery('.cartao16digitos').each(function(index,element) {
            jQuery(element).on('click', function ()
            {
                mascaraCartao.unmask().mask('9999 9999 9999 9999');
                mascaraCod.unmask().mask('999');
            });
        });

        jQuery('#nitrocielo_cartao_amex').each(function(index,element) {
            jQuery(element).on('click', function ()
            {
                console.log(this);
                mascaraCartao.unmask().mask('9999 999999 99999');
                mascaraCod.unmask().mask('9999');
            });
        });

        jQuery('#nitrocielo_cartao_diners').each(function(index,element) {
            jQuery(element).on('click', function ()
            {
                mascaraCartao.unmask().mask('9999 999999 9999');
                mascaraCod.unmask().mask('999');
            });
        });
        
        jQuery('#nitrocielo_cartao_aura').each(function(index,element) {
            jQuery(element).on('click', function ()
            {
                mascaraCartao.unmask().mask('9999 9999 9999 9999');
                mascaraCod.unmask().mask('999');
            });
        });
    <?php endif; ?>

    jQuery("#payment_form_nitrocielo input,#payment_form_nitrocielo select").blur(function (e)
    {
        Validation.validate(this)
    });
</script>