<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @title      Cielo pagamento com cartão de crédito (Brazil)
 * @category   payment
 * @package    Nitroecom_Cielo
 * @copyright  Copyright (c) 2017 Nitroecom (https://www.nitroecom.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Lucas Oliveira - Nitro e-com <www.nitroecom.com.br>
 */
		
?>

<?php echo $this->__('Nome no cartão: %s', $this->htmlEscape($this->getName())) ?><br/>
<?php echo $this->__('Bandeira do cartão: %s', $this->htmlEscape($this->getCcType())) ?><br/>
<?php echo $this->__('Últimos quatro números do cartão: **** **** **** %s', $this->htmlEscape($this->getQuatroUltimosNumeros())) ?><br/>
<?php echo $this->__('Data de expiração: %s', $this->htmlEscape($this->getValidade())) ?><br />
<?php echo $this->__('Número de Parcelas: %s', $this->getParcelas()) ?><br />
<?php echo $this->__('Id da transação (TID): %s', $this->htmlEscape($this->getTid())) ?>
